### ISSUE TITLE
dow2unix.js line 81: this.read(), no this function at all

### ISSUE THREAD

**Issue by DanielWLam** [JamesMGreene/node-dos2unix#5]
There is no such function at all. I can't run the task correctly...

**Comment by martinsik** [comment]
I have a similar problem. It always fails with:

```
/.../node_modules/dos2unix/lib/dos2unix.js:82
            len = data.length,
                      ^

TypeError: Cannot read property 'length' of null
    at Readable.onReadable (/.../node_modules/dos2unix/lib/dos2unix.js:82:23)
    at emitNone (events.js:86:13)
    at Readable.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at onEofChunk (_stream_readable.js:411:3)
    at readableAddChunk (_stream_readable.js:153:5)
    at Readable.push (_stream_readable.js:134:10)
    at ReadStream.<anonymous> (_stream_readable.js:780:10)
    at emitNone (events.js:91:20)
```

**Comment by raul1985singh** [comment]
I too was getting the same error.  I left the default options blank and provided the file_path while calling the process function. Hope this helps 

```
**OLD**
var defaultOptions = {
  glob: {
    cwd: __dirname
  },
  maxConcurrency: 50
};
var d2u = new D2UConverter(defaultOptions)

**NEW**
var d2u = new D2UConverter()
            .on('error', function(err) {
                logger.info("Error while converting file from dos2unix: "+err);
            })
            .on('end', function(stats) {
                logger.info("File converted from dos2unix: "+stats);
            });
d2u.process([file_path]);
```

**Comment by raul1985singh** [comment]
I too getting the same error.

**Comment by gronostajo** [comment]
Try this package instead, guys: https://www.npmjs.com/package/@dpwolfe/dos2unix
