### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by EmranAhmed** [JamesMGreene/node-dos2unix#6]
```

/xxxx/node_modules/dos2unix/lib/dos2unix.js:82
            len = data.length,
                      ^

TypeError: Cannot read property 'length' of null
    at Readable.onReadable (/xxxx/node_modules/dos2unix/lib/dos2unix.js:82:23)
    at emitNone (events.js:105:13)
    at Readable.emit (events.js:207:7)
    at emitReadable_ (_stream_readable.js:502:10)
    at emitReadable (_stream_readable.js:496:7)
    at onEofChunk (_stream_readable.js:481:3)
    at readableAddChunk (_stream_readable.js:209:5)
    at Readable.push (_stream_readable.js:197:10)
    at ReadStream.<anonymous> (_stream_readable.js:854:10)
    at emitNone (events.js:110:20)
    at ReadStream.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
error Command failed with exit code 1.
error Command failed with exit code 1.

```

**Comment by gronostajo** [comment]
This issue is fixed here: https://www.npmjs.com/package/@dpwolfe/dos2unix
There's also a similar pull request to this repo waiting to be accepted.

**Comment by EmranAhmed** [comment]
@gronostajo I will take a look, thank you 👍
